name: Destroy
on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3

      - name: Archivo TFVARS
        run: |
          cat <<EOF >> terraform/terraform.tfvars
          aws_access_key_id = "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws_session_token = "${{ secrets.AWS_SESSION_TOKEN }}"
          VPC_IPS          = ["10.0.0.0/16", "10.1.0.0/16"]
          Subnet_VPC1      = "10.0.1.0/24"
          Subnet_VPC2      = "10.1.1.0/24"
          Subnet_Private_VPC2 = "10.1.25.0/24"
          ftp_user         = "laura"
          ftp_password     = "laura"
          EOF

      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Descargar el artefacto
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/terraform.tfstate terraform/terraform.tfstate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'

      - name: Init Terraform
        run: terraform init
        working-directory: terraform

      - name: Destroy Terraform
        run: terraform destroy -auto-approve
        working-directory: terraform
